ifneq ($(strip $(U10_PANEL_PRIVATE_INCLUDE)),)
ccflags-y += -I$(U10_PANEL_PRIVATE_INCLUDE)
endif

obj-y += u10_panel.o
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include -I$(srctree)/drivers/misc/mediatek/lcm/inc -I$(srctree)/drivers/misc/mediatek/video/mt6755
